default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: window_agent_dev
  
test:
  <<: *default
  database: window_agent_test

production:
  <<: *default
  database: window_agent_pro